version: "3.9"
services:
  frontend:
    build: frontend
    ports:
      - "8080:8080"
    environment:
      - chokidar_usepolling=true
    command: npm run serve
    volumes:
      - ./frontend:/app
      - /app/node_modules # <---- this enables a much faster start/reload
  backend:
    build: backend
    environment:
      NODE_ENV: development
      MONGODB_CONNECTION_STRING: "mongodb://mongodb/twitter-web-clone"
    ports:
      - "3000:3000"
    command: npm run watch
    volumes:
      - ./backend:/app
  mongodb:
    image: mongo:5.0
    ports:
      - "37017:27017"
    # volumes:
    #   - ./data:/data/db
