
POST http://localhost:3000/users/register HTTP/1.1
content-type: application/json

# {"name": "Doğukan", "email": "hi@dogu.dev", "password":"123456", "confirmPassword":"123456" }
{"name": "Batuhan Batal", "email": "batuhan@gmail.com", "password":"1234561", "confirmPassword":"1234561" }

###

# authenticate a user
POST http://localhost:3000/users/login HTTP/1.1
content-type: application/json

# { "email": "hi@dogu.dev", "password":"123456"}
{ "email": "batuhan@gmail.com", "password":"1234561"}

###
# logout a user
GET http://localhost:3000/users/logout HTTP/1.1

###
# check logged in 
GET http://localhost:3000/users/login HTTP/1.1


###############################################

###
# create a new tweet
POST http://localhost:3000/tweets/new HTTP/1.1
content-type: application/json

{"content": "Merhaba World."}

###

# remove a tweet
DELETE http://localhost:3000/tweets/62cc652575266e7236b64ed0 HTTP/1.1
